version: '3'
services:
  p7:
     build: $PWD/dockerfiles/php7
     container_name: p7
     tty: true
     entrypoint: ["php-fpm"]
     networks:
       - default
     volumes:
       - $PWD/config/php7/:/usr/local/etc
       - $PWD/www/:/var/www/html/
       - $PWD/logs/php/:/var/log/php/
       - $PWD/xhgui-branch/:/var/www/xhgui/
  ng:
     image: nginx:1.15.7-alpine
     container_name: ng
     volumes:
       - $PWD/config/nginx/:/etc/nginx
       - $PWD/www/:/var/www/html
       - $PWD/logs/nginx:/var/log/nginx
       - $PWD/xhgui-branch/:/var/www/xhgui/
     depends_on:
       - p7
     links:
       - p7:php7
       - mongo:mongo
     ports:
       - "80:80"
     networks:
       - default
  redis:
    image: redis:5.0.3-alpine
    container_name: redis
    volumes:
      - $PWD/data/redis/:/data
      - $PWD/config/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    entrypoint: ["redis-server","/etc/redis/redis.conf"]
    networks:
      - default
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: es
    volumes:
      - $PWD/data/es6/:/user/share/elasticsearch/data/:rw
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - default
  kibana:
    image: kibana:6.7.0
    container_name: kibana
    volumes:
      - $PWD/config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - default
  mysql:
    image: mysql:5.7.28
    container_name: mysql
    volumes:
      - $PWD/data/mysql/:/var/lib/mysql/:rw
      - $PWD/config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=33063306
    networks:
      - default
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - $PWD/data/mongo:/data/db:rw
    restart: always
    networks:
      - default
  mongo_express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    links:
      - mongo
    environment: 
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night 
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress 
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress 
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin 
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
networks:
  default:
